//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  global: Global;
  globalConnection: GlobalConnection;
  legal: Legal;
  legalConnection: LegalConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryLegalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLegalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LegalFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  global?: InputMaybe<GlobalFilter>;
  legal?: InputMaybe<LegalFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Global | Legal | Folder;

export type PageBlocksHero = {
  __typename?: 'PageBlocksHero';
  title?: Maybe<Scalars['String']['output']>;
  heroFeatures?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  primaryButtonText?: Maybe<Scalars['String']['output']>;
  primaryButtonLink?: Maybe<Scalars['String']['output']>;
  secondaryButtonText?: Maybe<Scalars['String']['output']>;
  secondaryButtonLink?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksHostingFeaturesFeatures = {
  __typename?: 'PageBlocksHostingFeaturesFeatures';
  title?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksHostingFeatures = {
  __typename?: 'PageBlocksHostingFeatures';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<PageBlocksHostingFeaturesFeatures>>>;
};

export type PageBlocksVersionsMainCards = {
  __typename?: 'PageBlocksVersionsMainCards';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksVersionsVersionFeatures = {
  __typename?: 'PageBlocksVersionsVersionFeatures';
  title?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksVersions = {
  __typename?: 'PageBlocksVersions';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  mainCards?: Maybe<Array<Maybe<PageBlocksVersionsMainCards>>>;
  versionFeatures?: Maybe<Array<Maybe<PageBlocksVersionsVersionFeatures>>>;
};

export type PageBlocksExtendDescriptionItems = {
  __typename?: 'PageBlocksExtendDescriptionItems';
  title?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksExtendDescription = {
  __typename?: 'PageBlocksExtendDescription';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PageBlocksExtendDescriptionItems>>>;
};

export type PageBlocksLocationsLocations = {
  __typename?: 'PageBlocksLocationsLocations';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  latency?: Maybe<Scalars['Float']['output']>;
  qualification?: Maybe<Scalars['Float']['output']>;
  mc_icon?: Maybe<Scalars['String']['output']>;
  block?: Maybe<Scalars['String']['output']>;
  isExternal?: Maybe<Scalars['Boolean']['output']>;
};

export type PageBlocksLocations = {
  __typename?: 'PageBlocksLocations';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  locations?: Maybe<Array<Maybe<PageBlocksLocationsLocations>>>;
};

export type PageBlocksPricingPlansFeatures = {
  __typename?: 'PageBlocksPricingPlansFeatures';
  feature?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksPricingPlans = {
  __typename?: 'PageBlocksPricingPlans';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['Float']['output']>;
  discount?: Maybe<Scalars['String']['output']>;
  block?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<PageBlocksPricingPlansFeatures>>>;
};

export type PageBlocksPricing = {
  __typename?: 'PageBlocksPricing';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  discountText?: Maybe<Scalars['String']['output']>;
  plans?: Maybe<Array<Maybe<PageBlocksPricingPlans>>>;
};

export type PageBlocksPaymentMethodsMethods = {
  __typename?: 'PageBlocksPaymentMethodsMethods';
  name?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksPaymentMethods = {
  __typename?: 'PageBlocksPaymentMethods';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  methods?: Maybe<Array<Maybe<PageBlocksPaymentMethodsMethods>>>;
};

export type PageBlocksFaqSectionsQuestions = {
  __typename?: 'PageBlocksFaqSectionsQuestions';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
  video?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksFaqSections = {
  __typename?: 'PageBlocksFaqSections';
  title?: Maybe<Scalars['String']['output']>;
  questions?: Maybe<Array<Maybe<PageBlocksFaqSectionsQuestions>>>;
};

export type PageBlocksFaq = {
  __typename?: 'PageBlocksFaq';
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  variant?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<PageBlocksFaqSections>>>;
};

export type PageBlocks = PageBlocksHero | PageBlocksHostingFeatures | PageBlocksVersions | PageBlocksExtendDescription | PageBlocksLocations | PageBlocksPricing | PageBlocksPaymentMethods | PageBlocksFaq;

export type Page = Node & Document & {
  __typename?: 'Page';
  blocks?: Maybe<Array<Maybe<PageBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksHeroFilter = {
  title?: InputMaybe<StringFilter>;
  heroFeatures?: InputMaybe<StringFilter>;
  primaryButtonText?: InputMaybe<StringFilter>;
  primaryButtonLink?: InputMaybe<StringFilter>;
  secondaryButtonText?: InputMaybe<StringFilter>;
  secondaryButtonLink?: InputMaybe<StringFilter>;
};

export type PageBlocksHostingFeaturesFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageBlocksHostingFeaturesFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  features?: InputMaybe<PageBlocksHostingFeaturesFeaturesFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksVersionsMainCardsFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type PageBlocksVersionsVersionFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageBlocksVersionsFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  mainCards?: InputMaybe<PageBlocksVersionsMainCardsFilter>;
  versionFeatures?: InputMaybe<PageBlocksVersionsVersionFeaturesFilter>;
};

export type PageBlocksExtendDescriptionItemsFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type PageBlocksExtendDescriptionFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  items?: InputMaybe<PageBlocksExtendDescriptionItemsFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageBlocksLocationsLocationsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  latency?: InputMaybe<NumberFilter>;
  qualification?: InputMaybe<NumberFilter>;
  mc_icon?: InputMaybe<ImageFilter>;
  block?: InputMaybe<ImageFilter>;
  isExternal?: InputMaybe<BooleanFilter>;
};

export type PageBlocksLocationsFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  locations?: InputMaybe<PageBlocksLocationsLocationsFilter>;
};

export type PageBlocksPricingPlansFeaturesFilter = {
  feature?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageBlocksPricingPlansFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  discount?: InputMaybe<StringFilter>;
  block?: InputMaybe<ImageFilter>;
  features?: InputMaybe<PageBlocksPricingPlansFeaturesFilter>;
};

export type PageBlocksPricingFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  discountText?: InputMaybe<StringFilter>;
  plans?: InputMaybe<PageBlocksPricingPlansFilter>;
};

export type PageBlocksPaymentMethodsMethodsFilter = {
  name?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageBlocksPaymentMethodsFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  methods?: InputMaybe<PageBlocksPaymentMethodsMethodsFilter>;
};

export type PageBlocksFaqSectionsQuestionsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
  video?: InputMaybe<StringFilter>;
};

export type PageBlocksFaqSectionsFilter = {
  title?: InputMaybe<StringFilter>;
  questions?: InputMaybe<PageBlocksFaqSectionsQuestionsFilter>;
};

export type PageBlocksFaqFilter = {
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
  sections?: InputMaybe<PageBlocksFaqSectionsFilter>;
};

export type PageBlocksFilter = {
  hero?: InputMaybe<PageBlocksHeroFilter>;
  hostingFeatures?: InputMaybe<PageBlocksHostingFeaturesFilter>;
  versions?: InputMaybe<PageBlocksVersionsFilter>;
  extendDescription?: InputMaybe<PageBlocksExtendDescriptionFilter>;
  locations?: InputMaybe<PageBlocksLocationsFilter>;
  pricing?: InputMaybe<PageBlocksPricingFilter>;
  paymentMethods?: InputMaybe<PageBlocksPaymentMethodsFilter>;
  faq?: InputMaybe<PageBlocksFaqFilter>;
};

export type PageFilter = {
  blocks?: InputMaybe<PageBlocksFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type GlobalNav = {
  __typename?: 'GlobalNav';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type GlobalSocial = {
  __typename?: 'GlobalSocial';
  name?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  title?: Maybe<Scalars['String']['output']>;
  short_title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  nav?: Maybe<Array<Maybe<GlobalNav>>>;
  social?: Maybe<Array<Maybe<GlobalSocial>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlobalNavFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type GlobalSocialFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type GlobalFilter = {
  title?: InputMaybe<StringFilter>;
  short_title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  nav?: InputMaybe<GlobalNavFilter>;
  social?: InputMaybe<GlobalSocialFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type Legal = Node & Document & {
  __typename?: 'Legal';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date_updated?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type LegalFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date_updated?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type LegalConnectionEdges = {
  __typename?: 'LegalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Legal>;
};

export type LegalConnection = Connection & {
  __typename?: 'LegalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LegalConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateGlobal: Global;
  createGlobal: Global;
  updateLegal: Legal;
  createLegal: Legal;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationUpdateLegalArgs = {
  relativePath: Scalars['String']['input'];
  params: LegalMutation;
};


export type MutationCreateLegalArgs = {
  relativePath: Scalars['String']['input'];
  params: LegalMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  global?: InputMaybe<GlobalMutation>;
  legal?: InputMaybe<LegalMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  global?: InputMaybe<GlobalMutation>;
  legal?: InputMaybe<LegalMutation>;
};

export type PageBlocksHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroFeatures?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  primaryButtonText?: InputMaybe<Scalars['String']['input']>;
  primaryButtonLink?: InputMaybe<Scalars['String']['input']>;
  secondaryButtonText?: InputMaybe<Scalars['String']['input']>;
  secondaryButtonLink?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksHostingFeaturesFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksHostingFeaturesMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<PageBlocksHostingFeaturesFeaturesMutation>>>;
};

export type PageBlocksVersionsMainCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksVersionsVersionFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksVersionsMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  mainCards?: InputMaybe<Array<InputMaybe<PageBlocksVersionsMainCardsMutation>>>;
  versionFeatures?: InputMaybe<Array<InputMaybe<PageBlocksVersionsVersionFeaturesMutation>>>;
};

export type PageBlocksExtendDescriptionItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksExtendDescriptionMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PageBlocksExtendDescriptionItemsMutation>>>;
};

export type PageBlocksLocationsLocationsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  latency?: InputMaybe<Scalars['Float']['input']>;
  qualification?: InputMaybe<Scalars['Float']['input']>;
  mc_icon?: InputMaybe<Scalars['String']['input']>;
  block?: InputMaybe<Scalars['String']['input']>;
  isExternal?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageBlocksLocationsMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  locations?: InputMaybe<Array<InputMaybe<PageBlocksLocationsLocationsMutation>>>;
};

export type PageBlocksPricingPlansFeaturesMutation = {
  feature?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksPricingPlansMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  discount?: InputMaybe<Scalars['String']['input']>;
  block?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<PageBlocksPricingPlansFeaturesMutation>>>;
};

export type PageBlocksPricingMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  discountText?: InputMaybe<Scalars['String']['input']>;
  plans?: InputMaybe<Array<InputMaybe<PageBlocksPricingPlansMutation>>>;
};

export type PageBlocksPaymentMethodsMethodsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksPaymentMethodsMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  methods?: InputMaybe<Array<InputMaybe<PageBlocksPaymentMethodsMethodsMutation>>>;
};

export type PageBlocksFaqSectionsQuestionsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksFaqSectionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  questions?: InputMaybe<Array<InputMaybe<PageBlocksFaqSectionsQuestionsMutation>>>;
};

export type PageBlocksFaqMutation = {
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  variant?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<PageBlocksFaqSectionsMutation>>>;
};

export type PageBlocksMutation = {
  hero?: InputMaybe<PageBlocksHeroMutation>;
  hostingFeatures?: InputMaybe<PageBlocksHostingFeaturesMutation>;
  versions?: InputMaybe<PageBlocksVersionsMutation>;
  extendDescription?: InputMaybe<PageBlocksExtendDescriptionMutation>;
  locations?: InputMaybe<PageBlocksLocationsMutation>;
  pricing?: InputMaybe<PageBlocksPricingMutation>;
  paymentMethods?: InputMaybe<PageBlocksPaymentMethodsMutation>;
  faq?: InputMaybe<PageBlocksFaqMutation>;
};

export type PageMutation = {
  blocks?: InputMaybe<Array<InputMaybe<PageBlocksMutation>>>;
};

export type GlobalNavMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalSocialMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  short_title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  nav?: InputMaybe<Array<InputMaybe<GlobalNavMutation>>>;
  social?: InputMaybe<Array<InputMaybe<GlobalSocialMutation>>>;
};

export type LegalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date_updated?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageBlocksHeroFilter = {
  title?: StringFilter | null | undefined;
  heroFeatures?: StringFilter | null | undefined;
  primaryButtonText?: StringFilter | null | undefined;
  primaryButtonLink?: StringFilter | null | undefined;
  secondaryButtonText?: StringFilter | null | undefined;
  secondaryButtonLink?: StringFilter | null | undefined;
};

export type PageBlocksHostingFeaturesFeaturesFilter = {
  title?: StringFilter | null | undefined;
  content?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
};

export type PageBlocksHostingFeaturesFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  features?: PageBlocksHostingFeaturesFeaturesFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageBlocksVersionsMainCardsFilter = {
  title?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
};

export type PageBlocksVersionsVersionFeaturesFilter = {
  title?: StringFilter | null | undefined;
  content?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
};

export type PageBlocksVersionsFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  mainCards?: PageBlocksVersionsMainCardsFilter | null | undefined;
  versionFeatures?: PageBlocksVersionsVersionFeaturesFilter | null | undefined;
};

export type PageBlocksExtendDescriptionItemsFilter = {
  title?: StringFilter | null | undefined;
  content?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
};

export type PageBlocksExtendDescriptionFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  items?: PageBlocksExtendDescriptionItemsFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type PageBlocksLocationsLocationsFilter = {
  name?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  latency?: NumberFilter | null | undefined;
  qualification?: NumberFilter | null | undefined;
  mc_icon?: ImageFilter | null | undefined;
  block?: ImageFilter | null | undefined;
  isExternal?: BooleanFilter | null | undefined;
};

export type PageBlocksLocationsFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  locations?: PageBlocksLocationsLocationsFilter | null | undefined;
};

export type PageBlocksPricingPlansFeaturesFilter = {
  feature?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
};

export type PageBlocksPricingPlansFilter = {
  name?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  price?: NumberFilter | null | undefined;
  discount?: StringFilter | null | undefined;
  block?: ImageFilter | null | undefined;
  features?: PageBlocksPricingPlansFeaturesFilter | null | undefined;
};

export type PageBlocksPricingFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  discountText?: StringFilter | null | undefined;
  plans?: PageBlocksPricingPlansFilter | null | undefined;
};

export type PageBlocksPaymentMethodsMethodsFilter = {
  name?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  description?: StringFilter | null | undefined;
};

export type PageBlocksPaymentMethodsFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  methods?: PageBlocksPaymentMethodsMethodsFilter | null | undefined;
};

export type PageBlocksFaqSectionsQuestionsFilter = {
  question?: StringFilter | null | undefined;
  answer?: StringFilter | null | undefined;
  video?: StringFilter | null | undefined;
};

export type PageBlocksFaqSectionsFilter = {
  title?: StringFilter | null | undefined;
  questions?: PageBlocksFaqSectionsQuestionsFilter | null | undefined;
};

export type PageBlocksFaqFilter = {
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  variant?: StringFilter | null | undefined;
  sections?: PageBlocksFaqSectionsFilter | null | undefined;
};

export type PageBlocksFilter = {
  hero?: PageBlocksHeroFilter | null | undefined;
  hostingFeatures?: PageBlocksHostingFeaturesFilter | null | undefined;
  versions?: PageBlocksVersionsFilter | null | undefined;
  extendDescription?: PageBlocksExtendDescriptionFilter | null | undefined;
  locations?: PageBlocksLocationsFilter | null | undefined;
  pricing?: PageBlocksPricingFilter | null | undefined;
  paymentMethods?: PageBlocksPaymentMethodsFilter | null | undefined;
  faq?: PageBlocksFaqFilter | null | undefined;
};

export type PageFilter = {
  blocks?: PageBlocksFilter | null | undefined;
};

export type GlobalNavFilter = {
  label?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
};

export type GlobalSocialFilter = {
  name?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
};

export type GlobalFilter = {
  title?: StringFilter | null | undefined;
  short_title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  logo?: ImageFilter | null | undefined;
  nav?: GlobalNavFilter | null | undefined;
  social?: GlobalSocialFilter | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type LegalFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  date_updated?: DatetimeFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type PagePartsFragment = { __typename: 'Page', blocks: Array<
    | { __typename: 'PageBlocksHero', title: string | null, heroFeatures: Array<string | null> | null, primaryButtonText: string | null, primaryButtonLink: string | null, secondaryButtonText: string | null, secondaryButtonLink: string | null }
    | { __typename: 'PageBlocksHostingFeatures', titleLine1: string | null, titleLine2: string | null, features: Array<{ __typename: 'PageBlocksHostingFeaturesFeatures', title: string | null, content: string | null, icon: string | null } | null> | null }
    | { __typename: 'PageBlocksVersions', titleLine1: string | null, titleLine2: string | null, mainCards: Array<{ __typename: 'PageBlocksVersionsMainCards', title: string | null, image: string | null } | null> | null, versionFeatures: Array<{ __typename: 'PageBlocksVersionsVersionFeatures', title: string | null, content: string | null, icon: string | null } | null> | null }
    | { __typename: 'PageBlocksExtendDescription', titleLine1: string | null, titleLine2: string | null, items: Array<{ __typename: 'PageBlocksExtendDescriptionItems', title: string | null, content: string | null, image: string | null } | null> | null }
    | { __typename: 'PageBlocksLocations', titleLine1: string | null, titleLine2: string | null, locations: Array<{ __typename: 'PageBlocksLocationsLocations', name: string | null, description: string | null, latency: number | null, qualification: number | null, mc_icon: string | null, block: string | null, isExternal: boolean | null } | null> | null }
    | { __typename: 'PageBlocksPricing', titleLine1: string | null, titleLine2: string | null, discountText: string | null, plans: Array<{ __typename: 'PageBlocksPricingPlans', name: string | null, description: string | null, price: number | null, discount: string | null, block: string | null, features: Array<{ __typename: 'PageBlocksPricingPlansFeatures', feature: string | null, icon: string | null } | null> | null } | null> | null }
    | { __typename: 'PageBlocksPaymentMethods', titleLine1: string | null, titleLine2: string | null, title: string | null, methods: Array<{ __typename: 'PageBlocksPaymentMethodsMethods', name: string | null, image: string | null, description: string | null } | null> | null }
    | { __typename: 'PageBlocksFaq', titleLine1: string | null, titleLine2: string | null, variant: string | null, sections: Array<{ __typename: 'PageBlocksFaqSections', title: string | null, questions: Array<{ __typename: 'PageBlocksFaqSectionsQuestions', question: string | null, answer: string | null, video: string | null } | null> | null } | null> | null }
   | null> | null };

export type GlobalPartsFragment = { __typename: 'Global', title: string | null, short_title: string | null, description: string | null, logo: string | null, nav: Array<{ __typename: 'GlobalNav', label: string | null, href: string | null } | null> | null, social: Array<{ __typename: 'GlobalSocial', name: string | null, url: string | null, icon: string | null } | null> | null };

export type LegalPartsFragment = { __typename: 'Legal', title: string, description: string | null, date_updated: string | null, body: any };

export type PageQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageQuery = { page: { __typename: 'Page', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks: Array<
      | { __typename: 'PageBlocksHero', title: string | null, heroFeatures: Array<string | null> | null, primaryButtonText: string | null, primaryButtonLink: string | null, secondaryButtonText: string | null, secondaryButtonLink: string | null }
      | { __typename: 'PageBlocksHostingFeatures', titleLine1: string | null, titleLine2: string | null, features: Array<{ __typename: 'PageBlocksHostingFeaturesFeatures', title: string | null, content: string | null, icon: string | null } | null> | null }
      | { __typename: 'PageBlocksVersions', titleLine1: string | null, titleLine2: string | null, mainCards: Array<{ __typename: 'PageBlocksVersionsMainCards', title: string | null, image: string | null } | null> | null, versionFeatures: Array<{ __typename: 'PageBlocksVersionsVersionFeatures', title: string | null, content: string | null, icon: string | null } | null> | null }
      | { __typename: 'PageBlocksExtendDescription', titleLine1: string | null, titleLine2: string | null, items: Array<{ __typename: 'PageBlocksExtendDescriptionItems', title: string | null, content: string | null, image: string | null } | null> | null }
      | { __typename: 'PageBlocksLocations', titleLine1: string | null, titleLine2: string | null, locations: Array<{ __typename: 'PageBlocksLocationsLocations', name: string | null, description: string | null, latency: number | null, qualification: number | null, mc_icon: string | null, block: string | null, isExternal: boolean | null } | null> | null }
      | { __typename: 'PageBlocksPricing', titleLine1: string | null, titleLine2: string | null, discountText: string | null, plans: Array<{ __typename: 'PageBlocksPricingPlans', name: string | null, description: string | null, price: number | null, discount: string | null, block: string | null, features: Array<{ __typename: 'PageBlocksPricingPlansFeatures', feature: string | null, icon: string | null } | null> | null } | null> | null }
      | { __typename: 'PageBlocksPaymentMethods', titleLine1: string | null, titleLine2: string | null, title: string | null, methods: Array<{ __typename: 'PageBlocksPaymentMethodsMethods', name: string | null, image: string | null, description: string | null } | null> | null }
      | { __typename: 'PageBlocksFaq', titleLine1: string | null, titleLine2: string | null, variant: string | null, sections: Array<{ __typename: 'PageBlocksFaqSections', title: string | null, questions: Array<{ __typename: 'PageBlocksFaqSectionsQuestions', question: string | null, answer: string | null, video: string | null } | null> | null } | null> | null }
     | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageFilter | null | undefined;
}>;


export type PageConnectionQuery = { pageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks: Array<
          | { __typename: 'PageBlocksHero', title: string | null, heroFeatures: Array<string | null> | null, primaryButtonText: string | null, primaryButtonLink: string | null, secondaryButtonText: string | null, secondaryButtonLink: string | null }
          | { __typename: 'PageBlocksHostingFeatures', titleLine1: string | null, titleLine2: string | null, features: Array<{ __typename: 'PageBlocksHostingFeaturesFeatures', title: string | null, content: string | null, icon: string | null } | null> | null }
          | { __typename: 'PageBlocksVersions', titleLine1: string | null, titleLine2: string | null, mainCards: Array<{ __typename: 'PageBlocksVersionsMainCards', title: string | null, image: string | null } | null> | null, versionFeatures: Array<{ __typename: 'PageBlocksVersionsVersionFeatures', title: string | null, content: string | null, icon: string | null } | null> | null }
          | { __typename: 'PageBlocksExtendDescription', titleLine1: string | null, titleLine2: string | null, items: Array<{ __typename: 'PageBlocksExtendDescriptionItems', title: string | null, content: string | null, image: string | null } | null> | null }
          | { __typename: 'PageBlocksLocations', titleLine1: string | null, titleLine2: string | null, locations: Array<{ __typename: 'PageBlocksLocationsLocations', name: string | null, description: string | null, latency: number | null, qualification: number | null, mc_icon: string | null, block: string | null, isExternal: boolean | null } | null> | null }
          | { __typename: 'PageBlocksPricing', titleLine1: string | null, titleLine2: string | null, discountText: string | null, plans: Array<{ __typename: 'PageBlocksPricingPlans', name: string | null, description: string | null, price: number | null, discount: string | null, block: string | null, features: Array<{ __typename: 'PageBlocksPricingPlansFeatures', feature: string | null, icon: string | null } | null> | null } | null> | null }
          | { __typename: 'PageBlocksPaymentMethods', titleLine1: string | null, titleLine2: string | null, title: string | null, methods: Array<{ __typename: 'PageBlocksPaymentMethodsMethods', name: string | null, image: string | null, description: string | null } | null> | null }
          | { __typename: 'PageBlocksFaq', titleLine1: string | null, titleLine2: string | null, variant: string | null, sections: Array<{ __typename: 'PageBlocksFaqSections', title: string | null, questions: Array<{ __typename: 'PageBlocksFaqSectionsQuestions', question: string | null, answer: string | null, video: string | null } | null> | null } | null> | null }
         | null> | null } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: string;
}>;


export type GlobalQuery = { global: { __typename: 'Global', id: string, title: string | null, short_title: string | null, description: string | null, logo: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav: Array<{ __typename: 'GlobalNav', label: string | null, href: string | null } | null> | null, social: Array<{ __typename: 'GlobalSocial', name: string | null, url: string | null, icon: string | null } | null> | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: GlobalFilter | null | undefined;
}>;


export type GlobalConnectionQuery = { globalConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Global', id: string, title: string | null, short_title: string | null, description: string | null, logo: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav: Array<{ __typename: 'GlobalNav', label: string | null, href: string | null } | null> | null, social: Array<{ __typename: 'GlobalSocial', name: string | null, url: string | null, icon: string | null } | null> | null } | null } | null> | null } };

export type LegalQueryVariables = Exact<{
  relativePath: string;
}>;


export type LegalQuery = { legal: { __typename: 'Legal', id: string, title: string, description: string | null, date_updated: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LegalConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: LegalFilter | null | undefined;
}>;


export type LegalConnectionQuery = { legalConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Legal', id: string, title: string, description: string | null, date_updated: string | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksHero {
      title
      heroFeatures
      primaryButtonText
      primaryButtonLink
      secondaryButtonText
      secondaryButtonLink
    }
    ... on PageBlocksHostingFeatures {
      titleLine1
      titleLine2
      features {
        __typename
        title
        content
        icon
      }
    }
    ... on PageBlocksVersions {
      titleLine1
      titleLine2
      mainCards {
        __typename
        title
        image
      }
      versionFeatures {
        __typename
        title
        content
        icon
      }
    }
    ... on PageBlocksExtendDescription {
      titleLine1
      titleLine2
      items {
        __typename
        title
        content
        image
      }
    }
    ... on PageBlocksLocations {
      titleLine1
      titleLine2
      locations {
        __typename
        name
        description
        latency
        qualification
        mc_icon
        block
        isExternal
      }
    }
    ... on PageBlocksPricing {
      titleLine1
      titleLine2
      discountText
      plans {
        __typename
        name
        description
        price
        discount
        block
        features {
          __typename
          feature
          icon
        }
      }
    }
    ... on PageBlocksPaymentMethods {
      titleLine1
      titleLine2
      title
      methods {
        __typename
        name
        image
        description
      }
    }
    ... on PageBlocksFaq {
      titleLine1
      titleLine2
      variant
      sections {
        __typename
        title
        questions {
          __typename
          question
          answer
          video
        }
      }
    }
  }
}
    `;
export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  title
  short_title
  description
  logo
  nav {
    __typename
    label
    href
  }
  social {
    __typename
    name
    url
    icon
  }
}
    `;
export const LegalPartsFragmentDoc = gql`
    fragment LegalParts on Legal {
  __typename
  title
  description
  date_updated
  body
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const LegalDocument = gql`
    query legal($relativePath: String!) {
  legal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LegalParts
  }
}
    ${LegalPartsFragmentDoc}`;
export const LegalConnectionDocument = gql`
    query legalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LegalFilter) {
  legalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LegalParts
      }
    }
  }
}
    ${LegalPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    legal(variables: LegalQueryVariables, options?: C): Promise<{data: LegalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalQueryVariables, query: string}> {
        return requester<{data: LegalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalQueryVariables, query: string}, LegalQueryVariables>(LegalDocument, variables, options);
      },
    legalConnection(variables?: LegalConnectionQueryVariables, options?: C): Promise<{data: LegalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalConnectionQueryVariables, query: string}> {
        return requester<{data: LegalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalConnectionQueryVariables, query: string}, LegalConnectionQueryVariables>(LegalConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  